{% set version = "1.2.0" %}

package:
  name: fpyutils
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fpyutils/fpyutils-{{ version }}.tar.gz
  sha256: 8067c9558a500d8f2cff3f3dea6546d0cd403c99558cff87b3660878737a7a8e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - atomicwrites ==1.4.0
    - pyyaml ==5.3.1
    - requests ==2.24.0

test:
  imports:
    - fpyutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/frnmst/fpyutils
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: A collection of useful non-standard Python functions which aim to be simple to use, highly readable but not efficient

extra:
  recipe-maintainers:
    - ocefpaf
