{% set version = "2.0.1" %}

package:
  name: fpyutils
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fpyutils/fpyutils-{{ version }}.tar.gz
  sha256: 2312bfd8e3e98991682bc40f87dedb3576baa7f7bfb16d6b9792740424cccf0c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - atomicwrites >=1.4,<1.5
    - requests >=2.26,<2.27

test:
  imports:
    - fpyutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/frnmst/fpyutils
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: A collection of useful non-standard Python functions which aim to be simple to use, highly readable but not efficient

extra:
  recipe-maintainers:
    - ocefpaf
