{% set version = "1.2.1" %}

package:
  name: fpyutils
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fpyutils/fpyutils-{{ version }}.tar.gz
  sha256: 7d17cfdaccae0ed53a2fb3f5ca966b0c060e3a698d7baffd8c1e9d254c529652

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - atomicwrites >=1.4,<1.5
    - pyyaml >=5.3,<5.4
    - requests >=2.25,<2.26

test:
  imports:
    - fpyutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/frnmst/fpyutils
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: A collection of useful non-standard Python functions which aim to be simple to use, highly readable but not efficient

extra:
  recipe-maintainers:
    - ocefpaf
