{% set version = "1.1.2" %}

package:
  name: fpyutils
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fpyutils/fpyutils-{{ version }}.tar.gz
  sha256: e6d19c7e2066a961167397883b2e6b3eb127c4cdcbc7937eb3464fd365568299

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - atomicwrites ==1.4.0

test:
  imports:
    - fpyutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/frnmst/fpyutils
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: A collection of useful non-standard Python functions which aim to be simple to use, highly readable but not efficient

extra:
  recipe-maintainers:
    - ocefpaf
