{% set name = "fpyutils" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fpyutils-{{ version }}.tar.gz
  sha256: 8a5f0a6d99d23f1577671b8431f272702aa083eddb4e4fb76c3315fac268d92b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8,<4.0
    - setuptools >=39.2.0
    - pip
  run:
    - python >=3.8,<4.0

test:
  imports:
    - fpyutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/frnmst/fpyutils
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: A collection of useful non-standard Python functions which aim to be simple to use, highly readable but not efficient

extra:
  recipe-maintainers:
    - ocefpaf
