travis:
  secure:
    BINSTAR_TOKEN: O8lvO2QMdnjXSD6Nq1PxFqmBK2DiQrxw/obGgQbFwR+4pIrviRlpjloD6K3+m32jalmNTnVomKAhP1lEMxJq90ZwhJr0uCo4Eh5HGKG+cbm4eEzzvJlJQcQGhKpzAye7lmzr7uDKMZqSeyNA579I2k49lbPZp8zrF9OS5LiyQC6tHYqw8pwSVkobbVMaQPH0C42rQXagogIyvU/UYcw+YdLYKeVaxcFzp9+LLyOFlO4wHibVm324vBwhMuze38v0v3dc8hWcerI3bWRJUnysoGHI5X2mlmxrkadgrpDWcWXG5hWZdieS724M5UQjAbND92oJIGamHqc63NyKET3cwdQ3sqQiNIKrFabpLosJWewYH0xlQMzOIR57fWyKCnxDdNemAj2ZssgkIHfEfx1I6qIXayas93Ij1YWW+FO9X8EQENUogCyhy8tLd5c3OzdBnsa6/ncFbWUOwIHx3is6JZHU3FDYj4jxFNcjONmKRHPbBohlQlkGeBhEdeXg2qSLgkwUYnlkbVx0Lgt7Wy4hVK21+iyP9gzRzkkglQwp9rNwCUMNxqS8PfYiukGciSxAU3l7DHQQIdRi4rUL+b/q7nXueKEqkXmOu2m6tpx4JhUAhG6nQl8J4CBHLJ+jS/DNsU3Tiyxvm3vjQybixDKlvDYqTBonHh+5w4JLfbsS/Nw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
